name: store_flowable
description: Repository pattern support library for Dart with Stream API.
version: 0.4.1
homepage: https://github.com/KazaKago/StoreFlowable.dart

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  freezed_annotation: ^1.0.0
  rxdart: ^0.27.2
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.4
  freezed: ^1.0.0
  pedantic_mono: ^1.14.0+1
  test: ^1.19.0
