name: store_flowable
description: Repository pattern support library for Dart with Stream API.
version: 0.4.6
homepage: https://github.com/KazaKago/StoreFlowable.dart

environment:
  sdk: '<4.0.0'

dependencies:
  freezed_annotation: ^2.0.1
  rxdart: ^0.27.3
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^2.0.2
  pedantic_mono: ^1.18.0
  test: ^1.21.1
