name: store_flowable
description: Repository pattern support library for Dart with Stream API.
version: 1.0.0
homepage: https://github.com/KazaKago/StoreFlowable.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  freezed_annotation: ^0.14.0
  rxdart: ^0.26.0
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^1.11.5
  freezed: ^0.14.0+1
  pedantic_mono: ^1.11.0+2
  test: ^1.14.4
