name: store_flowable
description: Repository pattern support library for Dart with Stream API.
version: 0.2.1
homepage: https://github.com/KazaKago/StoreFlowable.dart

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  freezed_annotation: ^0.14.2
  rxdart: ^0.27.1
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.6
  freezed: ^0.14.2
  pedantic_mono: ^1.13.0+3
  test: ^1.17.10
